// microsoft-specific

#undef _ATL_VER
#undef __AVX__
#undef __AVX2__
#undef _CHAR_UNSIGNED
#undef __CLR_VER
#undef __cplusplus_cli
#undef __cplusplus_winrt
// #undef __COUNTER__
#undef __cplusplus
#undef _CPPRTTI
#undef _CPPUNWIND
#undef _DEBUG
#undef _DLL
#undef __FUNCDNAME__
#undef __FUNCSIG__
#undef __FUNCTION__
#undef _INTEGRAL_MAX_BITS
#undef _M_AMD64
#undef _M_ARM
#undef _M_CEE
#undef _M_CEE_PURE
#undef _M_CEE_SAFE
#undef _M_IX86
#undef _M_ARM_FP
#undef _M_IX86_FP
#undef _M_X64
#undef _MANAGED
#undef _MFC_VER
#undef _MSC_BUILD
#undef _MSC_EXTENSIONS
#undef _MSC_FULL_VER
#undef _MSC_VER
#undef __MSVC_RUNTIME_CHECKS
#undef _MT
#undef _NATIVE_WCHAR_T_DEFINED
#undef _OPENMP
#undef _VC_NODEFAULTLIB
#undef _WCHAR_T_DEFINED
#undef _WIN32
#undef _WIN64
