#+TITLE: Design the Type System


<2016-10-10 Mon>
#+BEGIN_EXAMPLE
HELIUM_INPUT_SPEC
int_iname.strlen = 151
addr_iname = 0x61300000de80
isnull_iname = 0
HELIUM_INPUT_SPEC_END
HELIUM_POI_INSTRUMENT
int_ifname.size = 1024
addr_ifname = 0x6059e0
int_iname.strlen = 151
addr_iname = 0x61300000de80
isnull_iname = 0
HELIUM_POI_INSTRUMENT_END
HELIUM_AFTER_POI
HELIUM_TEST_SUCCESS = true
#+END_EXAMPLE

I'm going to write a script to parse this output file, and generate a CSV file.
The CSV file will look like:



|       | input  |        |        | output  |         |         | status |
|-------+--------+--------+--------+---------+---------+---------+--------|
|       | input1 | input2 | input3 | output1 | output2 | output3 |        |
|-------+--------+--------+--------+---------+---------+---------+--------|
| test1 |        |        |        |         |         |         |        |
| test2 |        |        |        |         |         |         |        |
| test3 |        |        |        |         |         |         |        |

status code:
#+BEGIN_EXAMPLE
1 :: fail before input spec
2 :: fail before input spec end
3 :: fail before poi instrument
4 :: fail before poi instrument end
5 :: fail before "after poi"
6 :: fail after poi
7 :: success
#+END_EXAMPLE

After that, I'm ready to write an R script to compute the transfer functions.
I will only use the tests that have a status code of 5, in which the tests failed at exactly POI.
Later I might use
1. the tests that follow the same path, or
2. the tests that didn't follow the exactly same path,
   but have the same transfer function in terms of the variables in the failure condition.

* Input Spec
- Raw Input
- Json specification

** struct
it will be 
#+BEGIN_EXAMPLE
{field1: xxx, field2: yyy}
#+END_EXAMPLE
When passing to the outer level, it becomes:
#+BEGIN_EXAMPLE
{out_field1: {field1: xxx, field2: yyy}, ...}
#+END_EXAMPLE
finally for the outmost type, we have the variable name.

** =int var[8];=
the inner is:
#+BEGIN_EXAMPLE
{int: 0}
#+END_EXAMPLE
The outside is
#+BEGIN_EXAMPLE
[ {int: 0}, {int: 8} ]
#+END_EXAMPLE

** =char *=
the inner is
#+BEGIN_EXAMPLE
{strlen: 12, sizeof: 100}
#+END_EXAMPLE
The outer is
#+BEGIN_EXAMPLE
{HELIUM_POINTER: {strlen:12, sizeof: 100}}
#+END_EXAMPLE

** =int *=
the inner is
#+BEGIN_EXAMPLE
{int: 8}
#+END_EXAMPLE
The outer is
#+BEGIN_EXAMPLE
{HELIUM_POINTER: {int: 8}}
#+END_EXAMPLE

** ArgCV
The identification of ArgCV is in TypeFactory.
There's a class ArgCVType for this variable.

=char *argv[]=, =int argc=

#+BEGIN_EXAMPLE json
{ // 1
  argv_a: true, argv_b: false, // 1
  argv_f: {strlen: 4}, // 2
  argv_1: {strlen: 12}, argv_2: {strlen: 18} // 4
  argc: 1 + 1 + 2 + 4 = 8
}
#+END_EXAMPLE

The raw:
#+BEGIN_EXAMPLE
9
HELIUM_PROG -a -f fdsj 0123456789ab 0123456789abcdefgh
#+END_EXAMPLE
