#+TITLE: Machine Learning for Slicing

The data is the slice criteria generated by the following procedure:

1. run =generate-slice-criteria.sh= script, for =gzip1.7=, on two size configurations:
   10 per file and 100 per file.
2. use ~csurf -nogui -l /home/hebi/github/Helium/lib/csurf/plugin /path/to/benchmark/myproj~
   to generate slicing for each criteria.
   Some limitation for the data: no output for slicing set (initial, without removing duplication) larger than 10000
3. =uniq= the result. Note however, =uniq= will only remove duplicate for consecutive lines.
   A sort is required to further remove all duplications.

The format:
- every slicing criteria is outputed as =slice criteria: filename:line=,
  and  is prepended by a line ~======~
- the followings are the slices of this criteria, until another ~======~ or end of file


* How to run mlslice on these data

1. make the relative copy of the slice data, by removing /home/hebi/benchmark/gzip1.7/ with "".
   Note the result path should not be prefix with =/=
2. create the =tmp/= folder, containing slice files each slice per file.
   =./divide-slice.sh gzip-relative.txt=
3. run slice script by =./mlslice.sh /path/to/benchmark/folder/in/this/case/gzip1.7=,
   possibly redirect output to a csv file.
